config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  post 'login' => 'main#create'

  resources :main

  resources :posts do
    resources :votes
    resources :comments
  end

  resources :comments
  
  resources :comments do
    resources :comments
    resources :votes
  end

  get 'logout' => 'main#destroy'

  get 'past_posts' => 'posts#history'

  resources :users

  resources :users, :only => [:show] do 
    resources :votes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :votes, as: :votable
  has_many :comments, as: :commentable
  
  validates :title,
  presence: true,
  length: {minimum: 10, maximum:100}

  validates :body,
  presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :posts
	has_many :ratings, class_name: 'Vote'
	has_many :votes, as: :votable
	has_many :thoughts, class_name: 'Comment'
	

	validates :email,
	presence: true,
	uniqueness: {case_sensitive:false}

	validates_presence_of :password, on: :create

	def self.authenticate email, password
		User.find_by_email(email).try(:authenticate, password)
	end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	before_action :current_user

  	def current_user
  		@current_user ||= User.find_by_id(session[:user_id])
  	end

def is_authenticated?
    unless @current_user
      flash[:danger] = 'You need an account to do that!'
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create

    if params.key?(:post_id)
      thing = Post.find_by_id(params[:post_id])
  	elsif params.key?(:comment_id)
  	  thing = Comment.find_by_id(params[:comment_id])
    else
      render plain: "You can't comment on that!!"
      return
    end

    new_comment = thing.comments.create comment_params
    current_user.thoughts << new_comment
    redirect_to posts_(params[:post_id])_path
	end
	def comment_params
    	params.require(:comment).permit(:body)
  	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController


	def index
		@posts = Post.all
    @users = User.all
	end
	def new
		# @user = User.new
	end

	def create
	  user = User.authenticate(params[:user][:email],
      params[:user][:password])

    if user
      session[:user_id] = user.id
      flash[:success] = 'You are now logged in.'
      redirect_to root_path
    else

      flash[:danger] = 'Invalid email or password.'
      redirect_to root_path
    end
	end

  def destroy
    p= Post.find(params[:id])
    p.delete
    redirect_to root_path
  end

	def user_params
    	params.require(:user).permit(:email,:password)
  	end
  	def destroy
    session[:user_id] = nil
    flash[:info] = "You are logged out."
    redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :is_authenticated?


	def new
		@post = Post.new
	end

	def create
		@current_user.posts.create post_params
		redirect_to root_path
	end
	def destroy
    p= Post.find(params[:id])
    p.delete
    redirect_to root_path
  end

	def show
		@post=Post.find params[:id]
	end

	def post_params
    	params.require(:post).permit(:title,:body)
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		User.create user_params
		# session[:user_id] = user.id
		redirect_to root_path
	end

	def user_params
    	params.require(:user).permit(:name,:email,:password)
  	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	before_action :is_authenticated?

	def create 
		if params.key?(:post_id)
		thing = Post.find_by_id(params[:post_id])
		elsif params.key?(:user_id)
		thing = User.find_by_id(params[:user_id])
		elsif params.key?(:comment_id)
		thing = Comment.find_by_id(params[:comment_id])
		else
		render plain: "You can't vote on that!!"
		return
		end

		my_vote = thing.votes.find_by_user_id(current_user.id)
		vote_value = params[:button] == 'up' ? 1 :-1
		if my_vote.nil?
		new_vote = thing.votes.create value: vote_value
		current_user.ratings << new_vote
		else
		my_vote.value = vote_value
		my_vote.save
		end
		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerClone</title>

  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="row">
		<h1>The Hackedy Hackin' News.</h1>	
	</div>
	<div class="row">
		<div class="col-sm-7 col-sm-offset-1">
			<%= yield %>
		</div>
		<div class="col-sm-3 col-sm-offset-1">
			<% if @current_user %>
			<%= render 'shared/loggedin' %>
			<% else %>
			<%= render 'shared/login' %>
			<% end %>
		</div>
	</div>
</div>
</body>
</html>

app/views/main/index.html.erb
<h1>The News!</h1>

<%= render "shared/flash" %>

<% @posts.each do |post| %>

<div class="well">
	<div class="css-post">
		<%= bootstrap_form_for [post,Vote.new] do |f| %>
		<%= f.button "", value: 'up', class: 'css-votes btn btn-primary btn-xs glyphicon glyphicon-chevron-up' %>
		<%= f.button "", value: 'down', class: 'css-votes btn btn-primary btn-xs glyphicon glyphicon-chevron-down' %>
		<% end %>
		</div>
	<div class="css-post">
	<p class="css-post"><%= post.votes.reduce(0){ |sum,v| sum + v.value} %></p>
	<h2 class="css-post"><%= post.title %></h2>
	<p class="css-post"><%= post.body %></p>
	<p class="css-post"><%= post.user_id %></p>
	</div>
	<div class="css-post">
	<%= link_to "", post, method: :delete, class: "glyphicon glyphicon-trash pull-right" %>
	<%= link_to "This post!", post, class: "pull-right" %>
	</div>

</div>
	<% end %>

	
	

app/views/posts/history.html.erb
<h1>Your posts!</h1>
<% @current_user.posts.each do |post| %>
	<div>
	<h2><%= post.title %></h2>
	<p><%= post.body %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1>Create a new post!</h1>

<%= bootstrap_form_for @post do |f| %>
    <%= f.text_field :title, placeholder: "Title" %>
    <%= f.text_area :body, placeholder: "What's the post?"%>
    <%= f.submit "Create!"%>
    <%end%>

app/views/posts/show.html.erb
<h1>This Post!</h1>

<div>
<h2><%= @post.title %></h2>
<p><% @post.body %></p>
<%= bootstrap_form_for [@post, Comment.new] do |n| %>
	<%= n.text_field :body, placeholder: "Enter comment" %>
	<%= n.submit "Add Comment!" %>
<% end %>
	<% @post.comments.each do |c| %>
	<div>
		<%= bootstrap_form_for [c,Vote.new] do |f| %>
		<%= f.button "", value: 'up', class: 'css-votes btn btn-primary btn-xs glyphicon glyphicon-chevron-up' %>
		<%= f.button "", value: 'down', class: 'css-votes btn btn-primary btn-xs glyphicon glyphicon-chevron-down' %>
			<% end %>
		<p class="css-post"><%= c.votes.reduce(0){ |sum,v| sum + v.value} %></p>
		<div><%= c.user_id %></div>
		<div><%= c.body %></div>
		</div>	
		<% end %>

</div>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/shared/_loggedin.html.erb
<button class="btn btn-default"><%= link_to 'Create a post!', new_post_path %></button>
<button class="btn btn-default"><%= link_to 'See your posts', past_posts_path %></button>
<button class="btn btn-default"><%= link_to 'Logout', logout_path %></button>

app/views/shared/_login.html.erb
<h3>Log in to post and view your posts!</h3>
<%= form_for :user, url: login_path do |f| %>
    <%= f.text_field :email, placeholder: "Enter your email" %>
    <%= f.password_field :password, placeholder: "Enter your password"%>
    <%= f.submit "Login"%>
    <button><%= link_to "Sign up!", new_user_path %></button>
  	<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>
	<%= form_for @user do |f| %>
	<%= f.text_field :name, placeholder: "Enter your name" %>
    <%= f.text_field :email, placeholder: "Enter your email" %>
    <%= f.password_field :password, placeholder: "Enter your password"%>
    <%= f.submit "Sign up!"%>
    <% end %>